-- SCRIPT DE CRIAÇÃO DO BANCO CLYVO VET
-- DESENVOLVIDO PARA O CHALLENGE FIAP

-- 1. TABELA DE RAÇAS
CREATE TABLE CLY_TB_RACA (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL UNIQUE,
    propensao_doenca VARCHAR2(255),
    expectativa_vida NUMBER,
    cuidados_especiais VARCHAR2(500)
);

-- 2. TABELA DE TUTOR
CREATE TABLE CLY_TB_TUTOR (
    cpf VARCHAR2(14) PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    telefone VARCHAR2(20),
    email VARCHAR2(100),
    quantidade_pets NUMBER
);

-- 3. TABELA DE PETS
CREATE TABLE CLY_TB_PET (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    data_nascimento DATE NOT NULL,
    peso NUMBER(5,2),
    status_longevidade VARCHAR2(500),
    raca_id NUMBER,
    tutor_cpf VARCHAR2(14),
    CONSTRAINT fk_pet_raca FOREIGN KEY (raca_id) REFERENCES CLY_TB_RACA(id),
    CONSTRAINT fk_pet_tutor FOREIGN KEY (tutor_cpf) REFERENCES CLY_TB_TUTOR(cpf)
);

-- 4. CARGA INICIAL (RAÇAS PILOTO)
INSERT INTO CLY_TB_RACA (nome, propensao_doenca, expectativa_vida, cuidados_especiais) 
VALUES ('Golden Retriever', 'Displasia e Câncer', 12, 'Exames oncológicos anuais após os 7 anos');

INSERT INTO CLY_TB_RACA (nome, propensao_doenca, expectativa_vida, cuidados_especiais) 
VALUES ('Bulldog Francês', 'Problemas Respiratórios e Pele', 10, 'Evitar calor excessivo e exercícios intensos');

INSERT INTO CLY_TB_RACA (nome, propensao_doenca, expectativa_vida, cuidados_especiais) 
VALUES ('Border Collie', 'Displasia e Olhos', 15, 'Gasto de energia mental e física obrigatório');

INSERT INTO CLY_TB_RACA (nome, propensao_doenca, expectativa_vida, cuidados_especiais) 
VALUES ('Poodle', 'Cardíaco e Odontológico', 18, 'Limpeza de tártaro frequente');

INSERT INTO CLY_TB_RACA (nome, propensao_doenca, expectativa_vida, cuidados_especiais) 
VALUES ('Shih Tzu', 'Oftalmológico e Pulmão', 14, 'Cuidado redobrado com a higiene dos olhos');

COMMIT;
